import typescript from "@rollup/plugin-typescript";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source, please visit the GitHub repository of this plugin
*/
`;

const prod = process.env.BUILD === "production";

export default {
	input: "src/main.ts",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	output: {
		banner,
		file: "main.js",
		format: "cjs",
		exports: "default",
		sourcemap: prod ? false : "inline",
	},
	plugins: [
		typescript({
			tsconfig: "./tsconfig.json",
			inlineSourceMap: false,
			inlineSources: !prod,
			sourceMap: !prod,
		}),
	],
	treeshake: true,
};
